language: java
jdk:
  - oraclejdk7
  - openjdk7
install:
  - sh -e install-ios-driver.sh
script:
  - sh -e run-travis-ci-tests.sh
addons:
  sauce_connect: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#selion"
    on_success: always
    on_failure: always
    use_notice: true
